# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sunset & Sunrise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sunset & Sunrise
  pod 'GooglePlaces'
  pod 'GoogleMaps'
end
